services:
  - type: web
    name: my-flask-project
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "export PATH=$PATH:/usr/local/python3/bin && pip install gunicorn && gunicorn app:app"
    envVars:
      - key: GOOGLE_APPLICATION_CREDENTIALS_JSON
        value: $GOOGLE_APPLICATION_CREDENTIALS_JSON
      - key: SPREADSHEET_ID
        value: $SPREADSHEET_ID
      - key: NEW_SPREADSHEET_ID
        value: $NEW_SPREADSHEET_ID
      - key: NEW_SHEET_NAME
        value: $NEW_SHEET_NAME
