services:
  - type: web
    name: my-flask-project
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -w 4 -b 0.0.0.0:10000 app:app"
    envVars:
      - key: GOOGLE_APPLICATION_CREDENTIALS_JSON
        value: <your_credentials_json_as_string>
      - key: SPREADSHEET_ID
        value: 1REDUL2cKWozcH1wVOJOPBbySEGENA8t2RstmgrWQDY4
      - key: NEW_SPREADSHEET_ID
        value: 1ypknAict_qBGYcB9t-Fit8XsVBONMEkwBfKLKxXimWA
      - key: NEW_SHEET_NAME
        value: 価格表
