services:
  - type: web
    name: my-flask-project
    env: python
    plan: free
    envVars:
      - key: GOOGLE_APPLICATION_CREDENTIALS_JSON
        value: <your_credentials_json_as_string>
      - key: SPREADSHEET_ID
        value: 1REDUL2cKWozcH1wVOJOPBbySEGENA8t2RstmgrWQDY4
      - key: NEW_SPREADSHEET_ID
        value: 1mt3SnDPuMOXF4QQazKlJU1iLsL-4EThLGRhtfe-K7Wk
      - key: NEW_SHEET_NAME
        value: sheet1
